version: '2'
services:
    web-service:
        image: nginx:latest
        ports:
            - "8085:80"
        volumes:
            - ./code:/code
            - ./configs:/code/configs
            - ./images:/code/images
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - code-network
    php-fpm-service1:
        image: khanhicetea/php7-fpm-docker
        volumes:
            - ./code:/code
            - ./configs:/code/configs
            - ./images:/code/images
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - code-network
    php-fpm-service2:
        image: khanhicetea/php7-fpm-docker
        volumes:
            - ./code:/code
            - ./configs:/code/configs
            - ./images:/code/images
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - code-network
    php-fpm-service3:
        image: khanhicetea/php7-fpm-docker
        volumes:
            - ./code:/code
            - ./configs:/code/configs
            - ./images:/code/images
            - ./log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
        networks:
            - code-network

networks:
    code-network:
        driver: bridge
